spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/finance_dashboard
    username: finance_admin
    password: securepassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Automatically creates your tables based on Entities
    show-sql: true     # Helps debug queries in the console
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970 # 256-bit Hex Key
  expiration: 86400000 # 1 Day in milliseconds